default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: currency_exchange_development
  username: currency_exchange
  password: currency_exchange_password!
  host: localhost
  port: 5432

test:
  <<: *default
  database: currency_exchange_test
  username: currency_exchange
  password: currency_exchange_password!
  host: localhost
  port: 5432

production:
  <<: *default
  database: currency_exchange_production
  username: currency_exchange
  password: <%= ENV['CURRENCY_EXCHANGE_DATABASE_PASSWORD'] %>
